"""
API Agent - OpenAPI Specification Generator
Generates OpenAPI 3.1 specifications for services
"""
import logging
from typing import Dict, Any, Optional
from orchestrator.agents.base import BaseAgent

logger = logging.getLogger(__name__)

class APIAgent(BaseAgent):
    """Agent responsible for generating OpenAPI specifications"""
    
    def __init__(self):
        super().__init__("api")
        
    async def execute(
        self, 
        service_name: str, 
        requirement: str, 
        context: Dict[str, Any],
        providers: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Generate an OpenAPI 3.1 specification
        
        Args:
            service_name: Name of the service
            requirement: Service requirements
            context: Additional context from previous agents
            providers: Available providers (llm, vcs, etc.)
            
        Returns:
            Dict containing the generated OpenAPI spec
        """
        try:
            logger.info(f"🌐 Generating OpenAPI spec for service: {service_name}")
            
            llm_provider = providers.get("llm")
            if not llm_provider:
                raise ValueError("LLM provider not available")
            
            # Create API spec prompt
            api_prompt = self._build_api_prompt(service_name, requirement, context)
            
            # Generate API spec using LLM
            api_content = await llm_provider.generate_content(
                prompt=api_prompt,
                max_tokens=2500,
                temperature=0.2
            )
            
            # Fallback to template if LLM fails
            if not api_content:
                api_content = self._get_fallback_api(service_name, requirement, context)
            
            logger.info(f"✅ OpenAPI spec generated for service: {service_name}")
            
            return {
                "api_content": api_content,
                "filename": "openapi.yaml",
                "agent": self.name,
                "status": "completed"
            }
            
        except Exception as e:
            logger.error(f"❌ API spec generation failed: {e}")
            # Return fallback API spec
            return {
                "api_content": self._get_fallback_api(service_name, requirement, context),
                "filename": "openapi.yaml",
                "agent": self.name,
                "status": "completed_with_fallback",
                "error": str(e)
            }
    
    def _build_api_prompt(self, service_name: str, requirement: str, context: Dict[str, Any]) -> str:
        """Build the API specification generation prompt"""
        architecture_type = context.get("architecture_type", "microservice")
        
        return f"""You are an expert API designer creating an OpenAPI 3.1 specification.

Service Name: {service_name}
Requirements: {requirement}
Architecture Type: {architecture_type}

Create a comprehensive OpenAPI 3.1 YAML specification with:
1. Service metadata (title, version, description)
2. Health check endpoint: GET /health
3. RESTful endpoints based on the requirements
4. Proper HTTP methods (GET, POST, PUT, DELETE)
5. Request/response schemas with validation
6. Error responses (400, 404, 500)
7. Security schemes (JWT Bearer)
8. Component schemas for data models

Focus on:
- RESTful design principles
- Proper HTTP status codes
- Input validation
- Clear documentation
- Enterprise-grade API design

Format as valid YAML.
"""
    
    def _get_fallback_api(self, service_name: str, requirement: str, context: Dict[str, Any]) -> str:
        """Generate a fallback OpenAPI specification"""
        service_title = service_name.replace("-", " ").title()
        
        return f"""openapi: 3.1.0
info:
  title: {service_title} API
  version: 1.0.0
  description: |
    {service_title} service providing {requirement.lower()}
    
    Generated by DevFactory - Enterprise AI-Powered Platform
  contact:
    name: API Support
    email: api-support@company.com
  license:
    name: Proprietary
    
servers:
  - url: https://{service_name}.company.com
    description: Production server
  - url: https://{service_name}-staging.company.com
    description: Staging server

paths:
  /health:
    get:
      summary: Health check endpoint
      description: Returns the health status of the service
      operationId: healthCheck
      tags:
        - Health
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [ok]
                    example: ok
                  timestamp:
                    type: string
                    format: date-time
                  version:
                    type: string
                    example: "1.0.0"
        '503':
          description: Service is unhealthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
  /api/v1/resources:
    get:
      summary: List resources
      description: Retrieve a list of resources
      operationId: listResources
      tags:
        - Resources
      parameters:
        - name: page
          in: query
          description: Page number
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          description: Number of items per page
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Resource'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - BearerAuth: []
        
    post:
      summary: Create a new resource
      description: Create a new resource
      operationId: createResource
      tags:
        - Resources
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateResourceRequest'
      responses:
        '201':
          description: Resource created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - BearerAuth: []

  /api/v1/resources/{{id}}:
    get:
      summary: Get resource by ID
      description: Retrieve a specific resource by its ID
      operationId: getResource
      tags:
        - Resources
      parameters:
        - name: id
          in: path
          required: true
          description: Resource ID
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resource'
        '404':
          description: Resource not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      security:
        - BearerAuth: []

components:
  schemas:
    Resource:
      type: object
      required:
        - id
        - name
        - created_at
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the resource
        name:
          type: string
          description: Name of the resource
          maxLength: 100
        description:
          type: string
          description: Description of the resource
          maxLength: 500
        status:
          type: string
          enum: [active, inactive, pending]
          default: active
        created_at:
          type: string
          format: date-time
          description: Creation timestamp
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp
    
    CreateResourceRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: Name of the resource
          maxLength: 100
          minLength: 1
        description:
          type: string
          description: Description of the resource
          maxLength: 500
        status:
          type: string
          enum: [active, inactive]
          default: active
          
    Pagination:
      type: object
      properties:
        page:
          type: integer
          minimum: 1
        limit:
          type: integer
          minimum: 1
          maximum: 100
        total:
          type: integer
          minimum: 0
        pages:
          type: integer
          minimum: 0
    
    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
        message:
          type: string
          description: Human-readable error message
        details:
          type: object
          description: Additional error details
        timestamp:
          type: string
          format: date-time
        request_id:
          type: string
          format: uuid

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT Bearer token authentication

tags:
  - name: Health
    description: Health check endpoints
  - name: Resources
    description: Resource management endpoints
"""