"""
GitHub VCS Provider
GitHub integration for repository management
"""
import os
import logging
import tempfile
import shutil
from typing import Dict, Any, List, Optional
from google.cloud import secretmanager
from github import Github, InputGitTreeElement

logger = logging.getLogger(__name__)

class GitHubProvider:
    """GitHub VCS provider for repository operations"""
    
    def __init__(self, owner: str, repo: str, branch: str = "main"):
        self.owner = owner
        self.repo = repo
        self.branch = branch
        self.github = None
        self.repository = None
        self._setup_client()
    
    def _setup_client(self):
        """Initialize GitHub client"""
        try:
            # Get GitHub PAT
            pat = self._get_github_pat()
            if not pat:
                raise ValueError("GitHub PAT not available")
                
            self.github = Github(pat)
            self.repository = self.github.get_repo(f"{self.owner}/{self.repo}")
            
            logger.info(f"✅ GitHub client initialized for {self.owner}/{self.repo}")
            
        except Exception as e:
            logger.error(f"❌ Failed to initialize GitHub client: {e}")
            self.github = None
            self.repository = None
    
    def _get_github_pat(self) -> Optional[str]:
        """Get GitHub Personal Access Token"""
        try:
            # Try environment variable first
            env_pat = os.getenv("GITHUB_PAT")
            if env_pat:
                return env_pat.strip()
            
            # Try Secret Manager
            project_id = os.getenv("PROJECT_ID")
            if project_id:
                client = secretmanager.SecretManagerServiceClient()
                name = f"projects/{project_id}/secrets/GITHUB_PAT/versions/latest"
                response = client.access_secret_version(name=name)
                return response.payload.data.decode("utf-8").strip()
                
        except Exception as e:
            logger.error(f"❌ Failed to get GitHub PAT: {e}")
            
        return None
    
    async def commit_artifacts(
        self,
        service_name: str,
        artifacts: Dict[str, Any],
        commit_message: str
    ) -> Dict[str, Any]:
        """
        Commit generated artifacts to repository
        
        Args:
            service_name: Name of the service
            artifacts: Dictionary of generated artifacts
            commit_message: Commit message
            
        Returns:
            Dict with commit information
        """
        try:
            if not self.repository:
                raise ValueError("GitHub repository not initialized")
            
            logger.info(f"📚 Committing artifacts for {service_name} to {self.owner}/{self.repo}")
            
            # Get base commit
            base_ref = self.repository.get_git_ref(f"heads/{self.branch}")
            base_commit = self.repository.get_git_commit(base_ref.object.sha)
            
            # Build tree elements from artifacts
            tree_elements = []
            
            for artifact_key, artifact_data in artifacts.items():
                if isinstance(artifact_data, dict):
                    # Handle agent outputs
                    if "adr_content" in artifact_data:
                        tree_elements.append(
                            InputGitTreeElement(
                                path="ADR.md",
                                mode="100644",
                                type="blob",
                                content=artifact_data["adr_content"]
                            )
                        )
                    elif "api_content" in artifact_data:
                        tree_elements.append(
                            InputGitTreeElement(
                                path="openapi.yaml",
                                mode="100644", 
                                type="blob",
                                content=artifact_data["api_content"]
                            )
                        )
                    # Add more artifact types as needed
            
            # Add default files if no artifacts
            if not tree_elements:
                tree_elements.append(
                    InputGitTreeElement(
                        path="README.md",
                        mode="100644",
                        type="blob",
                        content=f"# {service_name.title()}\n\nGenerated by DevFactory"
                    )
                )
            
            # Create new tree
            new_tree = self.repository.create_git_tree(tree_elements, base_commit.tree)
            
            # Create commit
            new_commit = self.repository.create_git_commit(
                commit_message, new_tree, [base_commit]
            )
            
            # Update reference
            base_ref.edit(new_commit.sha)
            
            repository_url = f"https://github.com/{self.owner}/{self.repo}"
            
            logger.info(f"✅ Artifacts committed to {repository_url}")
            
            return {
                "repository_url": repository_url,
                "commit_sha": new_commit.sha,
                "commit_message": commit_message,
                "files_committed": len(tree_elements),
                "branch": self.branch
            }
            
        except Exception as e:
            logger.error(f"❌ Failed to commit artifacts: {e}")
            raise e
    
    async def health_check(self) -> Dict[str, Any]:
        """Health check for GitHub provider"""
        try:
            if not self.github or not self.repository:
                return {
                    "provider": "github",
                    "status": "unhealthy",
                    "error": "Client not initialized"
                }
            
            # Test repository access
            repo_info = self.repository.get_repo()
            
            return {
                "provider": "github",
                "status": "healthy",
                "repository": f"{self.owner}/{self.repo}",
                "branch": self.branch,
                "repository_accessible": True,
                "repository_url": repo_info.html_url
            }
            
        except Exception as e:
            return {
                "provider": "github", 
                "status": "unhealthy",
                "error": str(e)
            }
    
    async def create_repository(
        self,
        name: str,
        description: str = "",
        private: bool = False
    ) -> Dict[str, Any]:
        """Create a new repository"""
        try:
            if not self.github:
                raise ValueError("GitHub client not initialized")
            
            user = self.github.get_user()
            repo = user.create_repo(
                name=name,
                description=description,
                private=private,
                auto_init=True
            )
            
            return {
                "repository_url": repo.html_url,
                "clone_url": repo.clone_url,
                "ssh_url": repo.ssh_url,
                "name": repo.name
            }
            
        except Exception as e:
            logger.error(f"❌ Failed to create repository: {e}")
            raise e